// Sample scan result used when no real report is loaded.
export const SAMPLE_REPORT = {
  account_id: "123456789012",
  scan_time: new Date().toISOString(),
  summary: {
    total: 18,
    failed: 16,
    by_severity: { CRITICAL: 4, HIGH: 7, MEDIUM: 4, LOW: 3, INFO: 0 },
    by_check: {
      "S3-001": 3,
      "IAM-001": 2,
      "IAM-002": 5,
      "EC2-001": 6,
      "CT-001": 2,
    },
  },
  findings: [
    {
      check_id: "S3-001",
      check_name: "S3 Bucket Public Access",
      severity: "CRITICAL",
      status: "FAILED",
      resource_type: "AWS::S3::Bucket",
      resource_id: "arn:aws:s3:::my-public-bucket",
      region: "us-east-1",
      account_id: "123456789012",
      description: "Bucket 'my-public-bucket' does not have all Public Access Block settings enabled.",
      recommendation: "Enable S3 Block Public Access at both the account and bucket level. Review and tighten bucket ACLs and resource-based policies.",
      details: { public_access_block: { BlockPublicAcls: false, IgnorePublicAcls: false } },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "IAM-001",
      check_name: "IAM User With Admin Privileges",
      severity: "CRITICAL",
      status: "FAILED",
      resource_type: "AWS::IAM::User",
      resource_id: "arn:aws:iam::123456789012:user/dev-admin",
      region: "global",
      account_id: "123456789012",
      description: "IAM user 'dev-admin' has administrative privileges via: Managed policy: arn:aws:iam::aws:policy/AdministratorAccess.",
      recommendation: "Apply the principle of least privilege. Replace AdministratorAccess with scoped policies.",
      details: { reasons: ["Managed policy: arn:aws:iam::aws:policy/AdministratorAccess"] },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "EC2-001",
      check_name: "EC2 Security Group Open to World",
      severity: "CRITICAL",
      status: "FAILED",
      resource_type: "AWS::EC2::SecurityGroup",
      resource_id: "sg-0abc12345def67890",
      region: "us-east-1",
      account_id: "123456789012",
      description: "Security group 'launch-wizard-1' (sg-0abc12345def67890) allows inbound TCP port 22 from ['0.0.0.0/0'].",
      recommendation: "Restrict inbound rules to specific IP ranges. Use AWS Systems Manager Session Manager instead of opening SSH.",
      details: { sg_id: "sg-0abc12345def67890", protocol: "tcp", port_range: "22", open_cidrs: ["0.0.0.0/0"] },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "CT-001",
      check_name: "Root Account Usage Detected",
      severity: "CRITICAL",
      status: "FAILED",
      resource_type: "AWS::CloudTrail::Event",
      resource_id: "evt-abc123",
      region: "us-east-1",
      account_id: "123456789012",
      description: "Root account was used to perform 'ConsoleLogin' from IP 203.0.113.42.",
      recommendation: "The root account should never be used for day-to-day operations. Enable MFA on the root account.",
      details: { event_name: "ConsoleLogin", source_ip: "203.0.113.42" },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "IAM-002",
      check_name: "IAM Unused Access Keys",
      severity: "HIGH",
      status: "FAILED",
      resource_type: "AWS::IAM::AccessKey",
      resource_id: "arn:aws:iam::123456789012:user/old-ci/AccessKey/AKIAXXXXXXXXXXXXXXXX",
      region: "global",
      account_id: "123456789012",
      description: "Access key 'AKIAXXXXXXXXXXXXXXXX' for user 'old-ci' has not been used for 182 days.",
      recommendation: "Deactivate or delete access keys unused for more than 90 days.",
      details: { key_id: "AKIAXXXXXXXXXXXXXXXX", idle_days: 182 },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "EC2-001",
      check_name: "EC2 Security Group Open to World",
      severity: "HIGH",
      status: "FAILED",
      resource_type: "AWS::EC2::SecurityGroup",
      resource_id: "sg-0def98765abc43210",
      region: "eu-west-1",
      account_id: "123456789012",
      description: "Security group 'web-sg' allows inbound TCP port 443 from ['0.0.0.0/0', '::/0'].",
      recommendation: "Restrict inbound rules to known IP ranges or use a WAF/ALB layer.",
      details: { sg_id: "sg-0def98765abc43210", protocol: "tcp", port_range: "443", open_cidrs: ["0.0.0.0/0", "::/0"] },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "IAM-002",
      check_name: "IAM Unused Access Keys",
      severity: "HIGH",
      status: "FAILED",
      resource_type: "AWS::IAM::AccessKey",
      resource_id: "arn:aws:iam::123456789012:user/backup-svc/AccessKey/AKIAYYYYYYYYYYYYYY",
      region: "global",
      account_id: "123456789012",
      description: "Access key 'AKIAYYYYYYYYYYYYYY' for user 'backup-svc' is active but has NEVER been used. Created 120 days ago.",
      recommendation: "Deactivate or delete access keys unused for more than 90 days.",
      details: { key_id: "AKIAYYYYYYYYYYYYYY", age_days: 120, last_used: "Never" },
      timestamp: new Date().toISOString(),
    },
    {
      check_id: "S3-001",
      check_name: "S3 Bucket Public Access",
      severity: "MEDIUM",
      status: "FAILED",
      resource_type: "AWS::S3::Bucket",
      resource_id: "arn:aws:s3:::legacy-assets-bucket",
      region: "us-west-2",
      account_id: "123456789012",
      description: "Bucket 'legacy-assets-bucket' ACL grants READ to AllUsers.",
      recommendation: "Migrate public objects to CloudFront. Remove AllUsers ACL grants.",
      details: { acl_grantee: "http://acs.amazonaws.com/groups/global/AllUsers", permission: "READ" },
      timestamp: new Date().toISOString(),
    },
  ],
};
